version: '3.7'

services:
  cetonio:
    image: voko/cetonio
    build: 
      context: .
      dockerfile: Dockerfile
    # restart: always
    depends_on:
      - cikado
      - akrido
      - grilo
    ports:
      # ĉe IPv6 por havi la retpordon ne nur ĉe 0.0.0.0:8080, sed ankaŭ localhost:8080
      # uzu provizore:
      #   sysctl -w net.ipv4.ip_forward=1 
      # aŭ por havi tion konstante, aldonu en /etc/sysctl.conf
      #   net.ipv4.ip_forward = 1 
      # anakŭ vi povas aldoni en la gastiganto /etc/hosts
      #   127.0.0.1  example.com
      - 8080:8080
    secrets:
      # farenda: dividu agordon nesekretan kaj sekretan kaj uzu configs + secrets
      - source: redaktilo.cfg
        target: /home/cetonio/etc/redaktilo.cfg
      - source: redaktantoj
        target: /home/cetonio/etc/redaktantoj
    volumes:
      # ŝanĝita: ni nun uzas secrets anstatŭ bind 
      #- type: bind
      #  source: $HOME/etc
      #  target: /home/cetonio/etc
      #  read_only: true
      - type: volume
        source: sql
        target: /home/cetonio/sql
        #read_only: false
        #volume:
        #  nocopy: true

  cetonio-db:
    image: voko/cetonio
    build: 
      context: .
      dockerfile: Dockerfile
    command: ./download-inx-db.sh
    deploy:
      # aktualigu la datumbazon ĉiutage (kvankam en Revo ĝi momente estas malpli ofte renovigita)
      restart_policy:
        delay: 24h
    secrets:
      # farenda: dividu agordon nesekretan kaj sekretan kaj uzu configs + secrets
      - source: redaktilo.cfg
        target: /home/cetonio/etc/redaktilo.cfg
    volumes:
      # en ~/etc/ estu dosieroj redaktilo.cfg
      # La skemon vi povas trovi en Voko-Iloj.
      # ni uzas sekreton "redaktilo.cfg" anstataŭ bind
      #- type: bind
      #  source: $HOME/etc
      #  target: /home/cetonio/etc
      #  read_only: false
      - type: volume
        source: sql
        target: /home/cetonio/sql
        #read_only: false
        #volume:
        #  nocopy: true

  # servo por citaĵo-serĉo
  cikado:
    image: voko/cikado
    build: https://github.com/revuloj/voko-cikado.git
    #restart: always
    #expose:
    #  - 8082      

  # servo por vortanalizo
  akrido:
    image: voko/akrido
    build: https://github.com/revuloj/voko-akrido.git
    # restart: always
    #expose:
    #  - 8081

  # servo por sintakskontrolo per RelaxNG (Jing)
  grilo:
    image: voko/grilo
    build: https://github.com/revuloj/voko-grilo.git
    # restart: always
    #expose:
    #  - 8787

#  retpoŝtservilo, necesas nur se pluraj uzantoj uzas la redaktilon samtempe
#  tomocero:
#    image: voko-tomocero
#    build: https://github.com/revuloj/voko-tomocero.git

# en ~/etc/ estu dosieroj redaktilo.cfg kaj redaktantoj
# 1) la unuan oni povas kopii de cfg/redaktilo.cfg kaj agordi
# aldonante vian retpoŝtan konton. Por uzi Google-saluton vi
# bezonas registri vian propran ŝlosilon kun via retnomo (domajno)
# krome adaptu la posedanton al cetonio:
#   chown 1088 ~/etc/redaktilo.cfg
# 2) la dua (redaktantoj) estas listo de redaktanto-nomoj kaj retadresoj
# normale ni ricevos ĝin el la centra mysql-datumbazo poer aparta
# elŝuto-skripto, sed vi povas anstataŭe meti nur linion
#
# Via Nomo <via@retadre.so> <via@dua.retadre.so>

secrets:
  redaktilo.cfg:
    # adaptu redaktilo.cfg laŭ viaj bezonoj kaj 
    # a) registru per
    #   docker secret create ./redaktilo.cfg
    # uzante external: true
    # aŭ 
    # b) kopiu al ${HOME}/etc/redaktilo.cfg
    #external: true
    file: ${HOME}/etc/redaktilo.cfg
  redaktantoj:
    #external: true
    file: ${HOME}/etc/redaktantoj

volumes:
  sql:


  


