:-encoding(utf8).
entity(amp,&).
entity(lt,<).
entity(gt,>).
entity(apos,'\'').
entity(quot,'"').
entity('Ccirc','Ĉ').
entity(ccirc,ĉ).
entity('Gcirc','Ĝ').
entity(gcirc,ĝ).
entity('Hcirc','Ĥ').
entity(hcirc,ĥ).
entity('Jcirc','Ĵ').
entity(jcirc,ĵ).
entity('Scirc','Ŝ').
entity(scirc,ŝ).
entity('Ubreve','Ŭ').
entity(ubreve,ŭ).
entity('OElig','Œ').
entity(oelig,œ).
entity('Aacute','Á').
entity(aacute,á).
entity('Eacute','É').
entity(eacute,é).
entity('Iacute','Í').
entity(iacute,í).
entity('Oacute','Ó').
entity(oacute,ó).
entity('Uacute','Ú').
entity(uacute,ú).
entity('Agrave','À').
entity(agrave,à).
entity('Egrave','È').
entity(egrave,è).
entity('Igrave','Ì').
entity(igrave,ì).
entity('Ograve','Ò').
entity(ograve,ò).
entity('Ugrave','Ù').
entity(ugrave,ù).
entity('Acirc','Â').
entity(acirc,â).
entity('Ecirc','Ê').
entity(ecirc,ê).
entity('Icirc','Î').
entity(icirc,î).
entity('Ocirc','Ô').
entity(ocirc,ô).
entity('Ucirc','Û').
entity(ucirc,û).
entity(szlig,ß).
entity('Auml','Ä').
entity(auml,ä).
entity('Ouml','Ö').
entity(ouml,ö).
entity('Uuml','Ü').
entity(uuml,ü).
entity('Gbreve','Ğ').
entity(gbreve,ğ).
entity(inodot,ı).
entity('Idot','İ').
entity('Scedil','Ş').
entity(scedil,ş).
entity('Ccedil','Ç').
entity(ccedil,ç).
entity(minute,′).
entity(second,″).
entity(leftquot,„).
entity(rightquot,“).
entity(deg,°).
entity('Celsius',℃).
entity('Fahrenheit',℉).
entity(quadrat,²).
entity(cubic,³).
entity(para,§).
entity(dash,―).
entity(mdash,—).
entity(ndash,–).
entity(nbsp,'\240\').
entity('Euml','Ë').
entity(euml,ë).
entity('Iuml','Ï').
entity(iuml,ï).
entity('Aring','Å').
entity(aring,å).
entity('AElig','Æ').
entity(aelig,æ).
entity('Oslash','Ø').
entity(oslash,ø).
entity('Ntilde','Ñ').
entity(ntilde,ñ).
entity('Atilde','Ã').
entity(atilde,ã).
entity('Otilde','Õ').
entity(otilde,õ).
entity(middot,·).
entity('Abreve','Ă').
entity(abreve,ă).
entity('Tcedil','Ţ').
entity(tcedil,ţ).
entity('Alfa','Α').
entity(alfa,α).
entity(alfa_acute,ά).
entity('Alfa_acute','Ά').
entity(alfa_acute_subj,ᾴ).
entity(alfa_breve,ᾰ).
entity('Alfa_breve','Ᾰ').
entity(alfa_circ,ᾶ).
entity(alfa_circ_subj,ᾷ).
entity(alfa_densa,ἁ).
entity('Alfa_densa','Ἁ').
entity(alfa_densa_acute,ἅ).
entity('Alfa_densa_acute','Ἅ').
entity(alfa_densa_acute_subj,ᾅ).
entity('Alfa_densa_acute_Subj',ᾍ).
entity(alfa_densa_circ,ἇ).
entity('Alfa_densa_circ','Ἇ').
entity(alfa_densa_circ_subj,ᾇ).
entity('Alfa_densa_circ_Subj',ᾏ).
entity(alfa_densa_grave,ἃ).
entity('Alfa_densa_grave','Ἃ').
entity(alfa_densa_grave_subj,ᾃ).
entity('Alfa_densa_grave_Subj',ᾋ).
entity(alfa_densa_subj,ᾁ).
entity('Alfa_densa_Subj',ᾉ).
entity(alfa_grave,ὰ).
entity('Alfa_grave','Ὰ').
entity(alfa_grave_subj,ᾲ).
entity(alfa_makron,ᾱ).
entity('Alfa_makron','Ᾱ').
entity(alfa_psili,ἀ).
entity('Alfa_psili','Ἀ').
entity(alfa_psili_acute,ἄ).
entity('Alfa_psili_acute','Ἄ').
entity(alfa_psili_acute_subj,ᾄ).
entity('Alfa_psili_acute_Subj',ᾌ).
entity(alfa_psili_circ,ἆ).
entity('Alfa_psili_circ','Ἆ').
entity(alfa_psili_circ_subj,ᾆ).
entity('Alfa_psili_circ_Subj',ᾎ).
entity(alfa_psili_grave,ἂ).
entity('Alfa_psili_grave','Ἂ').
entity(alfa_psili_grave_subj,ᾂ).
entity('Alfa_psili_grave_Subj',ᾊ).
entity(alfa_psili_subj,ᾀ).
entity('Alfa_psili_Subj',ᾈ).
entity(alfa_subj,ᾳ).
entity('Alfa_Subj',ᾼ).
entity('Alfa_ton','Ά').
entity(alfa_ton,ά).
entity('Beta','Β').
entity(beta,β).
entity('Gamma','Γ').
entity(gamma,γ).
entity('Delta','Δ').
entity(delta,δ).
entity('Epsilon','Ε').
entity(epsilon,ε).
entity(epsilon_acute,έ).
entity('Epsilon_acute','Έ').
entity(epsilon_densa,ἑ).
entity('Epsilon_densa','Ἑ').
entity(epsilon_densa_acute,ἕ).
entity('Epsilon_densa_acute','Ἕ').
entity(epsilon_densa_grave,ἓ).
entity('Epsilon_densa_grave','Ἓ').
entity(epsilon_grave,ὲ).
entity('Epsilon_grave','Ὲ').
entity(epsilon_psili,ἐ).
entity('Epsilon_psili','Ἐ').
entity(epsilon_psili_acute,ἔ).
entity('Epsilon_psili_acute','Ἔ').
entity(epsilon_psili_grave,ἒ).
entity('Epsilon_psili_grave','Ἒ').
entity('Epsilon_ton','Έ').
entity(epsilon_ton,έ).
entity('Zeta','Ζ').
entity(zeta,ζ).
entity('Eta','Η').
entity(eta,η).
entity(eta_acute,ή).
entity('Eta_acute','Ή').
entity(eta_acute_subj,ῄ).
entity(eta_circ,ῆ).
entity(eta_circ_subj,ῇ).
entity(eta_densa,ἡ).
entity('Eta_densa','Ἡ').
entity(eta_densa_acute,ἥ).
entity('Eta_densa_acute','Ἥ').
entity(eta_densa_acute_subj,ᾕ).
entity('Eta_densa_acute_Subj',ᾝ).
entity(eta_densa_circ,ἧ).
entity('Eta_densa_circ','Ἧ').
entity(eta_densa_circ_subj,ᾗ).
entity('Eta_densa_circ_Subj',ᾟ).
entity(eta_densa_grave,ἣ).
entity('Eta_densa_grave','Ἣ').
entity(eta_densa_grave_subj,ᾓ).
entity('Eta_densa_grave_Subj',ᾛ).
entity(eta_densa_subj,ᾑ).
entity('Eta_densa_Subj',ᾙ).
entity(eta_grave,ὴ).
entity('Eta_grave','Ὴ').
entity(eta_grave_subj,ῂ).
entity(eta_psili,ἠ).
entity('Eta_psili','Ἠ').
entity(eta_psili_acute,ἤ).
entity('Eta_psili_acute','Ἤ').
entity(eta_psili_acute_subj,ᾔ).
entity('Eta_psili_acute_Subj',ᾜ).
entity(eta_psili_circ,ἦ).
entity('Eta_psili_circ','Ἦ').
entity(eta_psili_circ_subj,ᾖ).
entity('Eta_psili_circ_Subj',ᾞ).
entity(eta_psili_grave,ἢ).
entity('Eta_psili_grave','Ἢ').
entity(eta_psili_grave_subj,ᾒ).
entity('Eta_psili_grave_Subj',ᾚ).
entity(eta_psili_subj,ᾐ).
entity('Eta_psili_Subj',ᾘ).
entity(eta_subj,ῃ).
entity('Eta_Subj',ῌ).
entity('Eta_ton','Ή').
entity(eta_ton,ή).
entity('Theta','Θ').
entity(theta,θ).
entity('Jota','Ι').
entity(jota,ι).
entity(jota_acute,ί).
entity('Jota_acute','Ί').
entity(jota_breve,ῐ).
entity('Jota_breve','Ῐ').
entity(jota_circ,ῖ).
entity(jota_densa,ἱ).
entity('Jota_densa','Ἱ').
entity(jota_densa_acute,ἵ).
entity('Jota_densa_acute','Ἵ').
entity(jota_densa_circ,ἷ).
entity('Jota_densa_circ','Ἷ').
entity(jota_densa_grave,ἳ).
entity('Jota_densa_grave','Ἳ').
entity(jota_grave,ὶ).
entity('Jota_grave','Ὶ').
entity(jota_makron,ῑ).
entity('Jota_makron','Ῑ').
entity(jota_psili,ἰ).
entity('Jota_psili','Ἰ').
entity(jota_psili_acute,ἴ).
entity('Jota_psili_acute','Ἴ').
entity(jota_psili_circ,ἶ).
entity('Jota_psili_circ','Ἶ').
entity(jota_psili_grave,ἲ).
entity('Jota_psili_grave','Ἲ').
entity('Jota_ton','Ί').
entity(jota_ton,ί).
entity('Jota_trema','Ϊ').
entity(jota_trema,ϊ).
entity(jota_trema_acute,ΐ).
entity(jota_trema_circ,ῗ).
entity(jota_trema_grave,ῒ).
entity(jota_trema_ton,ΐ).
entity('Kappa','Κ').
entity(kappa,κ).
entity('Lambda','Λ').
entity(lambda,λ).
entity('My','Μ').
entity(my,μ).
entity('Ny','Ν').
entity(ny,ν).
entity('Xi','Ξ').
entity(xi,ξ).
entity('Omikron','Ο').
entity(omikron,ο).
entity(omikron_acute,ό).
entity('Omikron_acute','Ό').
entity(omikron_densa,ὁ).
entity('Omikron_densa','Ὁ').
entity(omikron_densa_acute,ὅ).
entity('Omikron_densa_acute','Ὅ').
entity(omikron_densa_grave,ὃ).
entity('Omikron_densa_grave','Ὃ').
entity(omikron_grave,ὸ).
entity('Omikron_grave','Ὸ').
entity(omikron_psili,ὀ).
entity('Omikron_psili','Ὀ').
entity(omikron_psili_acute,ὄ).
entity('Omikron_psili_acute','Ὄ').
entity(omikron_psili_grave,ὂ).
entity('Omikron_psili_grave','Ὂ').
entity('Omikron_ton','Ό').
entity(omikron_ton,ό).
entity('Pi','Π').
entity(pi,π).
entity('Rho','Ρ').
entity(rho,ρ).
entity(rho_densa,ῥ).
entity('Rho_densa','Ῥ').
entity(rho_psili,ῤ).
entity('Sigma','Σ').
entity(sigma,σ).
entity(sigma_fina,ς).
entity('Tau','Τ').
entity(tau,τ).
entity('Ypsilon','Υ').
entity(ypsilon,υ).
entity(ypsilon_acute,ύ).
entity('Ypsilon_acute','Ύ').
entity(ypsilon_breve,ῠ).
entity('Ypsilon_breve','Ῠ').
entity(ypsilon_circ,ῦ).
entity(ypsilon_densa,ὑ).
entity('Ypsilon_densa','Ὑ').
entity(ypsilon_densa_acute,ὕ).
entity('Ypsilon_densa_acute','Ὕ').
entity(ypsilon_densa_circ,ὗ).
entity('Ypsilon_densa_circ','Ὗ').
entity(ypsilon_densa_grave,ὓ).
entity('Ypsilon_densa_grave','Ὓ').
entity(ypsilon_grave,ὺ).
entity('Ypsilon_grave','Ὺ').
entity(ypsilon_makron,ῡ).
entity('Ypsilon_makron','Ῡ').
entity(ypsilon_psili,ὐ).
entity(ypsilon_psili_acute,ὔ).
entity(ypsilon_psili_circ,ὖ).
entity(ypsilon_psili_grave,ὒ).
entity('Ypsilon_ton','Ύ').
entity(ypsilon_ton,ύ).
entity('Ypsilon_trema','Ϋ').
entity(ypsilon_trema,ϋ).
entity(ypsilon_trema_acute,ΰ).
entity(ypsilon_trema_circ,ῧ).
entity(ypsilon_trema_grave,ῢ).
entity(ypsilon_trema_ton,ΰ).
entity('Phi','Φ').
entity(phi,φ).
entity('Chi','Χ').
entity(chi,χ).
entity('Psi','Ψ').
entity(psi,ψ).
entity('Omega','Ω').
entity(omega,ω).
entity(omega_acute,ώ).
entity('Omega_acute','Ώ').
entity(omega_acute_subj,ῴ).
entity(omega_circ,ῶ).
entity(omega_circ_subj,ῷ).
entity(omega_densa,ὡ).
entity('Omega_densa','Ὡ').
entity(omega_densa_acute,ὥ).
entity('Omega_densa_acute','Ὥ').
entity(omega_densa_acute_subj,ᾥ).
entity('Omega_densa_acute_Subj',ᾭ).
entity(omega_densa_circ,ὧ).
entity('Omega_densa_circ','Ὧ').
entity(omega_densa_circ_subj,ᾧ).
entity('Omega_densa_circ_Subj',ᾯ).
entity(omega_densa_grave,ὣ).
entity('Omega_densa_grave','Ὣ').
entity(omega_densa_grave_subj,ᾣ).
entity('Omega_densa_grave_Subj',ᾫ).
entity(omega_densa_subj,ᾡ).
entity('Omega_densa_Subj',ᾩ).
entity(omega_grave,ὼ).
entity('Omega_grave','Ὼ').
entity(omega_grave_subj,ῲ).
entity(omega_psili,ὠ).
entity('Omega_psili','Ὠ').
entity(omega_psili_acute,ὤ).
entity('Omega_psili_acute','Ὤ').
entity(omega_psili_acute_subj,ᾤ).
entity('Omega_psili_acute_Subj',ᾬ).
entity(omega_psili_circ,ὦ).
entity('Omega_psili_circ','Ὦ').
entity(omega_psili_circ_subj,ᾦ).
entity('Omega_psili_circ_Subj',ᾮ).
entity(omega_psili_grave,ὢ).
entity('Omega_psili_grave','Ὢ').
entity(omega_psili_grave_subj,ᾢ).
entity('Omega_psili_grave_Subj',ᾪ).
entity(omega_psili_subj,ᾠ).
entity('Omega_psili_Subj',ᾨ).
entity(omega_subj,ῳ).
entity('Omega_Subj',ῼ).
entity('Omega_ton','Ώ').
entity(omega_ton,ώ).
entity(c_Ju,'Ю').
entity(c_A,'А').
entity(c_B,'Б').
entity(c_C,'Ц').
entity(c_D,'Д').
entity(c_Je,'Е').
entity(c_F,'Ф').
entity(c_G,'Г').
entity(c_H,'Х').
entity(c_I,'И').
entity(c_J,'Й').
entity(c_K,'К').
entity(c_L,'Л').
entity(c_M,'М').
entity(c_N,'Н').
entity(c_O,'О').
entity(c_P,'П').
entity(c_Ja,'Я').
entity(c_R,'Р').
entity(c_S,'С').
entity(c_T,'Т').
entity(c_U,'У').
entity(c_Zh,'Ж').
entity(c_V,'В').
entity(c_Mol,'Ь').
entity(c_Y,'Ы').
entity(c_Z,'З').
entity(c_Sh,'Ш').
entity(c_E,'Э').
entity(c_Shch,'Щ').
entity(c_Ch,'Ч').
entity(c_Jo,'Ё').
entity(c_W,'Ў').
entity(c_Ib,'І').
entity(c_Gu,'Ґ').
entity(c_Jeu,'Є').
entity(c_Ji,'Ї').
entity(c_ju,ю).
entity(c_a,а).
entity(c_b,б).
entity(c_c,ц).
entity(c_d,д).
entity(c_je,е).
entity(c_f,ф).
entity(c_g,г).
entity(c_h,х).
entity(c_i,и).
entity(c_j,й).
entity(c_k,к).
entity(c_l,л).
entity(c_m,м).
entity(c_n,н).
entity(c_o,о).
entity(c_p,п).
entity(c_ja,я).
entity(c_r,р).
entity(c_s,с).
entity(c_t,т).
entity(c_u,у).
entity(c_zh,ж).
entity(c_v,в).
entity(c_mol,ь).
entity(c_y,ы).
entity(c_z,з).
entity(c_sh,ш).
entity(c_e,э).
entity(c_shch,щ).
entity(c_ch,ч).
entity(c_malmol,ъ).
entity(c_jo,ё).
entity(c_w,ў).
entity(c_ib,і).
entity(c_gu,ґ).
entity(c_jeu,є).
entity(c_ji,ї).
entity('Ccaron','Č').
entity(ccaron,č).
entity('Scaron','Š').
entity(scaron,š).
entity('Rcaron','Ř').
entity(rcaron,ř).
entity('Yacute','Ý').
entity(yacute,ý).
entity('Zcaron','Ž').
entity(zcaron,ž).
entity('Zdot','Ż').
entity(zdot,ż).
entity('Ncaron','Ň').
entity(ncaron,ň).
entity('Ecaron','Ě').
entity(ecaron,ě).
entity('Dcaron','Ď').
entity(dcaron,ď).
entity('Tcaron','Ť').
entity(tcaron,ť).
entity('Uring','Ů').
entity(uring,ů).
entity('Lacute','Ĺ').
entity(lacute,ĺ).
entity('Lcaron','Ľ').
entity(lcaron,ľ).
entity('Racute','Ŕ').
entity(racute,ŕ).
entity('Aogonek','Ą').
entity(aogonek,ą).
entity('Lstroke','Ł').
entity(lstroke,ł).
entity('Eogonek','Ę').
entity(eogonek,ę).
entity('Cacute','Ć').
entity(cacute,ć).
entity('Nacute','Ń').
entity(nacute,ń).
entity('Sacute','Ś').
entity(sacute,ś).
entity('Zacute','Ź').
entity(zacute,ź).
entity(alef,א).
entity(bet,ב).
entity(gimel,ג).
entity(dalet,ד).
entity(he,ה).
entity(vav,ו).
entity(zayin,ז).
entity(het,ח).
entity(tet,ט).
entity(yod,י).
entity(fkaf,ך).
entity(kaf,כ).
entity(lamed,ל).
entity(fmem,ם).
entity(mem,מ).
entity(fnun,ן).
entity(nun,נ).
entity(samekh,ס).
entity(ayin,ע).
entity(fpe,ף).
entity(pe,פ).
entity(ftsadi,ץ).
entity(tsadi,צ).
entity(qof,ק).
entity(resh,ר).
entity(shin,ש).
entity(tav,ת).
entity('Odblac','Ő').
entity(odblac,ő).
entity('Udblac','Ű').
entity(udblac,ű).
entity(amacron,ᗑ).
entity(emacron,ᗣ).
entity(gcommaaccent,ᗳ).
entity(imacron,ᗻ).
entity(kcommaaccent,ᘇ).
entity(lcommaaccent,ᘌ).
entity(ncommaaccent,ᘖ).
entity(omacron,ᘝ).
entity(rcommaaccent,ᘧ).
entity(umacron,ᘻ).
entity('Amacron',ᗐ).
entity('Emacron',ᗢ).
entity('Gcommaaccent',ᗲ).
entity('Imacron',ᗺ).
entity('Kcommaaccent',ᘆ).
entity('Lcommaaccent',ᘋ).
entity('Ncommaaccent',ᘕ).
entity('Omacron',ᘜ).
entity('Rcommaaccent',ᘦ).
entity('Umacron',ᘺ).
entity('Ycirc','Ŷ').
entity(ycirc,ŷ).
entity('Wgrave','Ẁ').
entity(wgrave,ẁ).
entity('Wacute','Ẃ').
entity(wacute,ẃ).
entity('Wuml','Ẅ').
entity(wuml,ẅ).
entity('Ygrave','Ỳ').
entity(ygrave,ỳ).
entity('Wcirc','Ŵ').
entity(wcirc,ŵ).
entity('Yuml','Ÿ').
entity(yuml,ÿ).
entity(a_komo,،).
entity(a_punktokomo,؛).
entity(a_demando,؟).
entity(a_hamza,ء).
entity(a_A_madda,آ).
entity(a_A_hamza_sure,أ).
entity(a_w_hamza,ؤ).
entity(a_A_hamza_sube,إ).
entity(a_y_hamza,ئ).
entity(a_A,ا).
entity(a_b,ب).
entity(a_t_marbuta,ة).
entity(a_t,ت).
entity(a_th,ث).
entity(a_j,ج).
entity(a_H,ح).
entity(a_kh,خ).
entity(a_d,د).
entity(a_dh,ذ).
entity(a_r,ر).
entity(a_z,ز).
entity(a_s,س).
entity(a_sh,ش).
entity(a_S,ص).
entity(a_D,ض).
entity(a_T,ط).
entity(a_Z,ظ).
entity(a_ayn,ع).
entity(a_gh,غ).
entity(a_tatwil,ـ).
entity(a_f,ف).
entity(a_q,ق).
entity(a_k,ك).
entity(a_l,ل).
entity(a_m,م).
entity(a_n,ن).
entity(a_h,ه).
entity(a_w,و).
entity(a_A_maqsura,ى).
entity(a_y,ي).
entity(a_fathatan,'ً').
entity(a_dammatan,'ٌ').
entity(a_kasratan,'ٍ').
entity(a_fatha,'َ').
entity(a_damma,'ُ').
entity(a_kasra,'ِ').
entity(a_shadda,'ّ').
entity(a_sukun,'ْ').
entity(a_madda_sure,'ٓ').
entity(a_hamza_sure,'ٔ').
entity(a_hamza_sube,'ٕ').
entity(a_A_sube,'ٖ').
entity(a_0,'٠').
entity(a_1,'١').
entity(a_2,'٢').
entity(a_3,'٣').
entity(a_4,'٤').
entity(a_5,'٥').
entity(a_6,'٦').
entity(a_7,'٧').
entity(a_8,'٨').
entity(a_9,'٩').
entity(a_procento,٪).
entity(a_dekumakomo,٫).
entity(a_milumakomo,٬).
entity(a_asterisko,٭).
entity(a_A_sure,'ٰ').
entity(a_A_wasla,ٱ).
entity(f_p,پ).
entity(f_ch,چ).
entity(f_zh,ژ).
entity(f_k,ک).
entity(f_g,گ).
entity(u_hy,ۀ).
entity(f_y,ی).
entity(f_0,'۰').
entity(f_1,'۱').
entity(f_2,'۲').
entity(f_3,'۳').
entity(f_4,'۴').
entity(f_5,'۵').
entity(f_6,'۶').
entity(f_7,'۷').
entity(f_8,'۸').
entity(f_9,'۹').
entity(a_fatha_A,'َا').
entity(a_kasra_y,'ِي').
entity(a_damma_w,'ُو').
entity(t_tsheg,་).
entity(t_ka,ཀ).
entity(t_kha,ཁ).
entity(t_ga,ག).
entity(t_nga,ང).
entity(t_ca,ཅ).
entity(t_cha,ཆ).
entity(t_ja,ཇ).
entity(t_nya,ཉ).
entity(t_ta,ཏ).
entity(t_tha,ཐ).
entity(t_da,ད).
entity(t_na,ན).
entity(t_pa,པ).
entity(t_pha,ཕ).
entity(t_ba,བ).
entity(t_ma,མ).
entity(t_tsa,ཙ).
entity(t_tsha,ཚ).
entity(t_dza,ཛ).
entity(t_wa,ཝ).
entity(t_zha,ཞ).
entity(t_za,ཟ).
entity('t_-a',འ).
entity(t_ya,ཡ).
entity(t_ra,ར).
entity(t_la,ལ).
entity(t_sha,ཤ).
entity(t_sa,ས).
entity(t_ha,ཧ).
entity(t_a,ཨ).
entity(t_gigu,'ི').
entity(t_shabchu,'ུ').
entity(t_drengbu,'ེ').
entity(t_naro,'ོ').
entity(t_kata,'ྐ').
entity(t_khata,'ྑ').
entity(t_gata,'ྒ').
entity(t_ngata,'ྔ').
entity(t_cata,'ྕ').
entity(t_chata,'ྖ').
entity(t_jata,'ྗ').
entity(t_nyata,'ྙ').
entity(t_tata,'ྟ').
entity(t_thata,'ྠ').
entity(t_data,'ྡ').
entity(t_nata,'ྣ').
entity(t_pata,'ྤ').
entity(t_phata,'ྥ').
entity(t_bata,'ྦ').
entity(t_mata,'ྨ').
entity(t_tsata,'ྩ').
entity(t_tshata,'ྪ').
entity(t_dzata,'ྫ').
entity(t_wasur,'ྭ').
entity(t_zhata,'ྮ').
entity(t_zata,'ྯ').
entity(t_achung,'ྰ').
entity(t_yata,'ྱ').
entity(t_rata,'ྲ').
entity(t_lata,'ླ').
entity(t_shata,'ྴ').
entity(t_sata,'ྶ').
entity(t_hata,'ྷ').
entity(t_ata,'ྸ').
entity(zwnj,'‌').
entity(zwj,'‍').
entity(lrm,'‎').
entity(rlm,'‏').
entity(lre,'‪').
entity(rle,'‫').
entity(pdf,'‬').
entity(lro,'‭').
entity(rlo,'‮').
entity('Z','Zamenhof').
entity(tZ,'trad. Zamenhof').
entity('B','Kabe').
entity(tB,'trad. Kabe').
entity('K','Kalocsay').
entity('G','Grabowski').
entity('AtZ','Andersen, trad. Zamenhof').
entity('PtK','Prus, trad. Kabe').
entity('AE','Akademio de Esperanto').
entity('X','Malnova testamento').
entity('N','Nova testamento').
entity('F','Fundamento de Esperanto').
entity('PrV','Proverbaro').
entity('EE','Esenco kaj Estonteco').
entity('Fabeloj','Fabeloj').
entity('Far1','La Faraono, 1a vol.').
entity('Far2','La Faraono, 2a vol.').
entity('Far3','La Faraono, 3a vol.').
entity('FE','Ekzercaro, §').
entity('Gen','Genezo').
entity('Eli','Eliro').
entity('Lev','Levidoj').
entity('Nom','Nombroj').
entity('Rea','Readmono').
entity('Jos','Josuo').
entity('Jug','Juĝistoj').
entity('Rut','Rut').
entity('Sa1','I. Samuel').
entity('Sa2','II. Samuel').
entity('Re1','I. Reĝoj').
entity('Re2','II. Reĝoj').
entity('Kr1','I. Kroniko').
entity('Kr2','II. Kroniko').
entity('Ezr','Ezra').
entity('Neh','Neĥemja').
entity('Est','Ester').
entity('Ijo','Ijob').
entity('Psa','Psalmaro').
entity('Sen','Sentencoj').
entity('Pre','Predikanto').
entity('Alt','Alta Kanto').
entity('Jes','Jesaja').
entity('Jer','Jeremia').
entity('Plo','Plorkanto').
entity('Jeh','Jeĥezkel').
entity('Dan','Daniel').
entity('Hos','Ĥosea').
entity('Joe','Joel').
entity('Amo','Amos').
entity('Oba','Obadja').
entity('Jon','Jona').
entity('Mih','Miĥa').
entity('Nah','Naĥum').
entity('Hab','Ĥabakuk').
entity('Zeh','Zeĥarja').
entity('Mal','Malaĥi').
entity('Mat','S. Mateo').
entity('Mar','S. Marko').
entity('Luk','S. Luko').
entity('Joh','S. Johano').
entity('Ago','La agoj').
entity('Rom','Al la Romanoj').
entity('Ko1','I. Korintanoj').
entity('Ko2','II. Korintanoj').
entity('Gal','Al la Galatoj').
entity('Efe','Al la Efesanoj').
entity('Fil','Al la Filipanoj').
entity('Kol','Al la Koloseanoj').
entity('Te1','I. Tesalonikanoj').
entity('Te2','II. Tesalonikanoj').
entity('Ti1','I. Timoteo').
entity('Ti2','II. Timoteo').
entity('Tit','Al Tito').
entity('Flm','Al Filemon').
entity('Heb','Al la Hebreoj').
entity('Jak','De Jakobo').
entity('Pe1','I. Petro').
entity('Pe2','II. Petro').
entity('Jo1','I. Johano').
entity('Jo2','II. Johano').
entity('Jo3','III. Johano').
entity('Jud','De Judas').
entity('Apo','Apokalipso').
entity('KompLeks','http://www.esperanto.mv.ru/ESP/kframe.html').
entity('Bib','../dok/bibliogr.html#').
entity('Monato','https://www.monato.be').
entity('Viki','http://eo.wikipedia.org/wiki').
entity('Vikio','http://eo.wikipedia.org/w/index.php?title=').
entity(dbp,'http://dbpedia.org/').
entity(dbpr,'http://dbpedia.org/resource/').
entity('ViVo','http://kono.be/cgi-bin/vivo/').
entity('ViVoTrd','http://kono.be/cgi-bin/vivo/ViVo.cgi?pagxo=').
entity('AdE','http://www.akademio-de-esperanto.org').
entity('WCU','https://upload.wikimedia.org/wikipedia/commons').
entity('WCW','https://commons.wikimedia.org/wiki').
